### ISSUE TITLE
SDK: modernize tsconfig module resolution (classic node10 pins viem to 2.49.0)

### ISSUE THREAD

**Issue by nud3l** [bob-collective/bob#1115]
## Problem

`@gobob/bob-sdk`'s `tsconfig.json` uses `module: commonjs` with **no `moduleResolution` set**, so it defaults to classic **`node10`** resolution. Classic resolution ignores a dependency's `exports` map and instead pulls the dependency's TypeScript **source** (`.ts`) into the SDK's own compile. `skipLibCheck: true` only skips `.d.ts`, not `.ts`, so those sources get type-checked.

Concretely, this makes the SDK build fail on **`ox`** (a transitive dep of `viem`): viem ≥ ~2.53 pulls `ox` 0.14.29/0.14.30, whose `tempo/KeyAuthorization.ts` has a type error:

```
node_modules/.pnpm/ox@0.14.29/.../ox/tempo/KeyAuthorization.ts(537,3): error TS2322:
  Type '{ account?: ... }' is not assignable to type 'Signed<bigint, number, `0x${string}`>'.
```

## Impact

- The SDK is currently **pinned to `viem` exactly `2.49.0`** (the last version whose `ox` 0.14.20 type-checks) — see #1113, where the HyperEVM `multicall3` fix forced a viem bump but couldn't go past 2.49.0.
- This is out of step with **bob-collective/ui**, which is on `viem ^2.53.1`. The UI builds fine because it uses **modern module resolution** (`nodenext` / `bundler` via `@gobob/typescript-config`), which follows `ox`'s `exports` to its `.d.ts` (skipped by `skipLibCheck`).
- Any future viem bump is blocked until this is fixed.

## Root cause confirmed

Setting `moduleResolution: bundler` on the SDK's tsconfig makes **viem 2.53.1 build with zero `ox` errors** — i.e. this is purely the SDK's outdated resolution config, not a viem/ox limitation.

## Proposed fix

Modernize the SDK's module resolution to match the UI (e.g. adopt `@gobob/typescript-config`, or `moduleResolution: nodenext`/`bundler`). The catch: modern resolution is coupled to the module **output** format, and the SDK is a plain CommonJS package (`main: dist/index.js`, no `type`, no `exports` map). So this also requires either:
- `module: nodenext` + adding explicit `.js` extensions to relative imports (keeps CJS emit when `type` is unset), **or**
- a dual CJS/ESM build with a proper `exports` map.

## Acceptance criteria

- [ ] SDK builds on `viem` ≥ 2.53 (matching the UI) with no `ox` type errors.
- [ ] CommonJS consumers still load it — verify `@gobob/gateway-cli` (Node, `require`) builds and runs against the updated SDK.
- [ ] viem un-pinned from the exact `2.49.0` (see #1113) to a range compatible with the UI.

## Refs
- #1113 (SDK HyperEVM — pinned viem 2.49.0 due to this)
- #1114 (gateway-cli HyperEVM)
- bob-collective/ui `pnpm-workspace.yaml` (viem catalog `^2.53.1` + global override)
